### ISSUE TITLE
Deletion of database not working

### ISSUE THREAD

**Issue by jforseth210** [sqlitebrowser/dbhub.io#128] opened 2020-05-29 02:14 UTC
Just signed up for dbhub.io using my github account. 
Uploaded my database.
Tried to remove the database by clicking the settings cog, going to destructive options, and clicking "Delete database".
"Yes, delete it."
Clicking redirects to my homepage, where the database is still present.

**Comment by justinclift** [comment] 2020-05-29 03:54
Oh, that's not good.  Investigating now. :smile:

**Comment by jforseth210** [comment] 2020-05-29 04:00
Thanks! Let me know if I can provide any more information.

**Comment by justinclift** [comment] 2020-05-29 04:27
No worries. :smile:

The logs are showing an error message saying the delete was rejected, as it would have violated a foreign key constraint (a type of database integrity check thing).

Pretty sure this is the first time that error has shown itself for DBHub.io stuff.  Should have it fixed in a few hours though (will need to setup a full replicate to trace things out, etc).

**Comment by justinclift** [comment] 2020-05-29 09:36
@jforseth210 Do you time to try that deletion again?

In theory, the problem is now fixed.  But having you verify it just to be on the safe side is probably a good idea. :smile:

**Comment by jforseth210** [comment] 2020-05-29 16:08
Yep. It worked now. Thank you!

**Comment by justinclift** [comment] 2020-05-29 22:44
You're welcome @jforseth210, thanks for letting us know about the problem and helping with the fix. :smile:

**Closed** 2020-06-28 11:08 UTC
